service: basic-example

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: api/hello
          method: get
